version: "3.7"

services:
  # Railsアプリケーション
  app:
    build: .

    # プロセスが正しく後始末されるようにする
    init: true

    ports:
      - "3000:3000"

    volumes:
      # node_modulesはイメージの中にあるものを使う
      - /app/node_modules
      - .:/app
